### ISSUE TITLE
Can not compile anymore - Debian sid

### ISSUE THREAD

**Issue by tsointsoin** [projectM-visualizer/projectm#263]
Hello, I can't compile projectM anymore :

./autogen
./configure
make -j4

......

/bin/bash ../../libtool  --tag=CXX   --mode=link g++  -g -O2 -pthread -std=c++11 -static -fPIC /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread    -o projectM-jack qprojectM-jack.o ConfigFile.o ../projectM-qt/libprojectM_qt.a -ljack /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   ../libprojectM/libprojectM.la -lGL  -ldl  -pthread
libtool: link: g++ -g -O2 -pthread -std=c++11 -fPIC /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -o projectM-jack qprojectM-jack.o ConfigFile.o /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -pthread  ../projectM-qt/libprojectM_qt.a -ljack -lpthread ../libprojectM/.libs/libprojectM.a -L/usr/X11R6/lib /usr/lib/x86_64-linux-gnu/libGL.so -lm -lXext -lX11 -ldl -pthread
/usr/bin/ld: ../projectM-qt/libprojectM_qt.a(qprojectm_mainwindow.o): undefined reference to symbol '_ZN5QIconC1Ev@@Qt_5'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libQt5Gui.so: error adding symbols: DSO missing from command line

apt-cache policy libqt5gui5
libqt5gui5:
  Installé : 5.12.5+dfsg-2

**Comment by tsointsoin** [comment]
Kinda solved by adding "/usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so" at the end of the command line :

g++ -g -O2 -pthread -std=c++11 -fPIC /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -o projectM-jack qprojectM-jack.o ConfigFile.o /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -pthread  ../projectM-qt/libprojectM_qt.a -ljack -lpthread ../libprojectM/.libs/libprojectM.a -L/usr/X11R6/lib /usr/lib/x86_64-linux-gnu/libGL.so -lm -lXext -lX11 -ldl -lpthread /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so

**Comment by coast77777777777** [comment]
33ca67c8aee841c0ddb5cc1b868628eef0eeed79
is this resolved now?

**Comment by tsointsoin** [comment]
Still not resolved for me, I need to add /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so or the link fails.
