### ISSUE TITLE
dyld: Library not loaded: @rpath/SDL2.framework/Versions/A/SDL2

### ISSUE THREAD

**Issue by MartyMaro** [projectM-visualizer/projectm#88]
I'm trying to install projectM-SDL-mac, but it returns:

```
dyld: Library not loaded: @rpath/SDL2.framework/Versions/A/SDL2
  Referenced from: /Users/marty/Downloads/projectM-SDL-mac/./SDLprojectM
  Reason: image not found
Abort trap: 6
```

Shouldn't SDL2 be embedded into the SDLprojectM binary? How can I solve this issue?

**Comment by revmischa** [comment]
its not a package so the framework doesn't come bundled. it should be in the zip though. try getting the framework and dropping it in. https://www.libsdl.org/release/SDL2-2.0.8.dmg

**Comment by MartyMaro** [comment]
Thx for the quick reply. It's not in the zip, so I downloaded the framework and dropped it into the folder where the binary is located, but this does not work. Where does  `@rpath` point to?

**Comment by revmischa** [comment]
That's a great question

**Comment by revmischa** [comment]
Should be fixed here https://github.com/projectM-visualizer/projectm/pull/26/commits/92f3fb4e2d0a351a36340b025aeefbd899d83556#diff-5c44692eccb37aa51cf9643ca5bd06edR426

It's in "runtime search paths"

**Comment by revmischa** [comment]
Give the latest release a try and see if this issue is fixed now: https://github.com/projectM-visualizer/projectm/releases/tag/v3.1.0-beta1

**Comment by MartyMaro** [comment]
Thanks for the release. I've tested both variants (pkg and tar). I got the projectM standalone app that works, but has no audio input, obviously. The visualiser is still not listed in iTunes, though. Are there any more steps required?

**Comment by revmischa** [comment]
The iTunes plugin needs some updating as well, a binary of it isn't included in that release

**Comment by revmischa** [comment]
itunes issue: #93

**Comment by clerdson** [comment]
remove SDL library/frameworks
install_name_tool -change @rpath/SDL2.framework/Versions/A/SDL2 /path/to/actual/SDL2.framework/Versions/A/SDL2 your_executable


---clang++ main.cpp /Users/clerdson/Desktop/glew/src/glew.c -I/Users/clerdson/Desktop/glew/include -I/Users/clerdson/Desktop/SDL2.framework/Headers -F/Users/clerdson/Desktop -framework SDL2   -framework OpenGL
